### ISSUE TITLE
leave lp_ out of default display

### ISSUE THREAD

**Issue by mhandreae** [jgabry/SHINYstan#23]
Could we leave lp_ out of most default displays. it is on a different scale and makes the original parameters of interest difficult to see. To select then all of the original parameters is cumbersome. Alternatively, there should we a way to DESELECT the one nuisance parameter, e.g. lp_ (instead of selecting a couple). 
Proposition: Inputing "-mu" {"minus" mu} in the selection window would show all EXCEPT mu?

**Comment by jgabry** [comment]
I don't think we should leave lp__ out of the tables, but I think you're right about leaving it out of the main multi-parameter plot because it does screw up the scale. I'll change it so it's left out of the plot by default but we can allow the user to add it back in if they want.
